spring:
  datasource:
    url: jdbc:mysql://flutter.cmnco2is8n58.us-east-1.rds.amazonaws.com:3306/flutter
    username: admin
    password: Nck250621

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: caoky.sonha@gmail.com
    password: 'iisrdsbtaljjucag'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
